In [4]:
!pip install pandas

^C


In [7]:
import pandas as pd
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 2.0.3
numpy            : 1.25.0
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.0.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli

In [2]:
import numpy as np

In [3]:
import numpy
numpy.version.version

'1.25.0'

In [6]:
a = np.array([1,2,3])  #pass in 1 dimensional array - a matirx of 1 list of array 
a     # value printed with array([1,2,3]) including
print(a)   # array value  ----->  printed  [1,2,3] only 
#a.ndim     # .ndim - gets the array dimension  -here its 1 dimesional array
a.shape  # .shape   ------ > get shape or size of matix or array  here its 1*3 matrix


[1 2 3]


(3,)

     --------------------------------------- 10.7/10.7 MB 73.5 kB/s eta 0:00:00
     ------------------------------------ 502.3/502.3 KB 181.0 kB/s eta 0:00:00
     ------------------------------------ 341.8/341.8 KB 175.4 kB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\ACER\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [47]:
a.dtype  # to know hpw muchmemory occupied by each array ----> using obj.dtype

dtype('int32')

###  [  [    ,   ]   ]   --> represents a matrix with single row and n columns
 note seee the elemtns with bracket/s and the outbracket as one matrix entity 

#### [  [    ,   ] , [    ,     ]  ]   --> represents matrix with two  row  and n columns  --> one matrix entity

    ####   [      [  [    ,   ] , [    ,     ]  ]   ,    [  [    ,   ] , [    ,     ]  ]  ]   --> has matrices with two outbrackets and comma between them  two matrices as entitites ---> 2 matrxi entity 

In [8]:
#b.dtype



# two dimenasional array  --> - a  single matirx with 2D array  or also called   simply matrix of size 2*3 
b = np.array([[1.8, 3.4, 5.6], [2.3, 4.5 , 6.8]])  # 2D array/matrix -- represnted using list within a list-[[]] -a type of nesting
#print (b)
#b.ndim    # .ndim - gets the array dimension  -here its 2 dimesional array
b.shape   # .shape   ------ > get shape or size of matix or array  here its 2*3 matrix shows matrix of m rows *n columns 
        # -because -[1.8, 3.4, 5.6] -a sinlge list  represents one  row
    
          # [2.3, 4.5 , 6.8]   - 2nd row but there are 3 columns within each row so 2*3 matrix 
        # so m number of lists reprsetns m rows and then count the columns say the columns are n --so m * n matrix
#b.dtype

(2, 3)

In [54]:
# 3D array or also called  --> --> - a  single matirx with 3D array    
#simply 3D matrix -represnted using list within a list within a list 3[]s -[ [ [ ] ] ] 
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #-a 3*3 matrix 
#print(c)
#c.ndim   # .ndim - gets the array dimension  -here its 3 dimesional array
c.shape
#c.dtype


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


(1, 3, 3)

In [28]:
a = np.array([[1,1],[2,2]])
b = np.array([[3,4],[6,5]])
print (a)
print (b)

print(a*b)            # single value item wise direct computation in numpy cant do it in lists 


[[1 1]
 [2 2]]
[[3 4]
 [6 5]]
[[ 3  4]
 [12 10]]


##  matrix with n dimenisons

In [10]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])   # --> contians 2 matrices each with 2D array -->one matrix as [[1,2],[3,4]]
print(d)                                     # --> another  matrix entity  as [[5,6],[7,8]
d.ndim
#d.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [11]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)  # (array, n, axis =y) -->n times each element of array is repeated 
                                # and the axis directionof repeation where the array is displayed
                            # if axis =0 the direction of repeatation is vertical across the column 
print(r1)                  # if axis =1 the direction of repeatation is in horizontal across the row

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
r1 = np.repeat(arr,3, axis=1) # # if axis =1 the direction of repeatation is in horizontal across the row
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [23]:
output = np.ones((5,5))
print(output[1:-1])


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Load in NumPy (remember to pip install numpy first)

In [ ]:
import numpy as np

### The Basics

In [24]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [31]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [26]:
# Get Dimension
a.ndim

1

In [30]:
b.ndim

2

In [32]:
# Get Shape
b.shape

(2, 3)

In [34]:
# Get Type
b.dtype

dtype('float64')

In [35]:
# Get Size
a.itemsize

4

In [36]:
# Get total size
a.nbytes

12

In [37]:
# Get number of elements
a.size

3

In [ ]:
### Accessing/Changing specific elements, rows, columns, etc

In [38]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [39]:
# Get a specific element [r, c]
a[1, 5]

13

In [40]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [42]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [44]:
a[1,5] = 20

a[:,4] = [1,2]
print(a)

[[ 1  2  1  4  1  6  7]
 [ 8  9  2 11  2 20 14]]


## *3-d example

In [45]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [47]:
# Get specific element (work outside in)
b[1,0,1]

6

In [50]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [51]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [55]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [57]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [58]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [60]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.66095683, 0.82440117],
       [0.46489053, 0.48966827],
       [0.76358673, 0.5775623 ],
       [0.9167466 , 0.66582954]])

In [62]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  0,  7],
       [ 7, -4, -1],
       [-3, -4,  1]])

### Mathematics

In [74]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [66]:
a + 2

array([3, 4, 5, 6])

In [67]:
a - 2

array([-1,  0,  1,  2])

In [68]:
a * 2

array([2, 4, 6, 8])

In [69]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [70]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [71]:
a ** 2

array([ 1,  4,  9, 16])

In [72]:
# Take the sin
np.cos(a) # radian values


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### numpy broadcasting

In [79]:
from numpy import array
x = array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
y = array([1,1,1])
print(y)
z = x + y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 1 1]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [80]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [81]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [89]:
stats = np.array([[1,6,8],[9,5,2]])
stats

array([[1, 6, 8],
       [9, 5, 2]])

In [83]:
np.min(stats)

1

In [91]:
np.max(stats, axis=0)

array([9, 6, 8])

In [ ]:
np.sum(stats, axis=0)

### Reorganizing Arrays

In [98]:
import numpy as np
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.T)

after = before.reshape((4,2))
print(after)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [101]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## split input and output data

In [105]:
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


# split train and test data

In [106]:
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]
